---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: vault-secrets-operator-install
spec:
  complianceType: musthave
  complianceConfig:
    catalogSourceUnhealthy: NonCompliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Delete
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: high
  upgradeApproval: None
  subscription:
    channel: stable
    name: vault-secrets-operator
    namespace: vault-secrets-operator
    source: certified-operators
    sourceNamespace: openshift-marketplace
