---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: policies
resources:
  - active-hub-clusters.yaml
  - baremetal-clusters.yaml
  - hub-clusters.yaml
  - non-production-clusters.yaml
  - odf-clusters.yaml
  - openshift-clusters.yaml
  - passive-hub-clusters.yaml
  - production-clusters.yaml
  - self-remediation-clusters.yaml
  - virtualization-host-clusters.yaml
  - workload-clusters.yaml
