---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: odf-clusters
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: odf-enabled
              operator: In
              values:
                - 'true'
