---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: hub01-cluster-config
policyDefaults:
  namespace: policies
  policySets:
    - hub01-cluster-config
placementBindingDefaults:
  name: hub01-cluster-config-binding

policies:
  - name: cluster-networking
    complianceType: mustonlyhave
    manifests:
      - path: cluster-networking

  - name: hub01-cluster-proxy
    remediationAction: inform
    manifests:
      - path: cluster-proxy.yaml

  - name: hub01-odf-configure
    remediationAction: enforce
    dependencies:
      - name: odf-operator
        compliance: Compliant
    manifests:
      - path: storage

  - name: hub01-cluster-version
    remediationAction: inform
    policySets:
      - hub01-cluster-config
    manifests:
      - path: cluster-version

  - name: hub01-managed-cluster
    remediationAction: enforce
    manifests:
      - path: managedcluster.yaml

policySets:
  - name: hub01-cluster-config
    placement:
      placementName: hub01
