apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: BareMetal
    cluster.open-cluster-management.io/clusterset: default
    environment: production
    name: hub01
    vendor: OpenShift
    hub-role: active
  name: hub01
spec:
  hubAcceptsClient: true