---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: ocp1-cluster-config
policyDefaults:
  namespace: policies
  policySets:
    - ocp1-cluster-config
placementBindingDefaults:
  name: ocp1-cluster-config-binding

policies:
  - name: cluster-networking
    complianceType: mustonlyhave
    manifests:
      - path: cluster-networking

  - name: ocp1-cluster-proxy
    remediationAction: inform
    manifests:
      - path: cluster-proxy.yaml

  - name: ocp1-odf-configure
    remediationAction: enforce
    dependencies:
      - name: odf-operator
        compliance: Compliant
    manifests:
      - path: storage

  - name: ocp1-cluster-version
    remediationAction: inform
    policySets:
      - ocp1-cluster-config
    manifests:
      - path: cluster-version

policySets:
  - name: ocp1-cluster-config
    placement:
      placementName: ocp1
