apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: BareMetal
    cluster.open-cluster-management.io/clusterset: default
    environment: production
    name: ocp2
    vendor: OpenShift
  name: ocp2
spec:
  hubAcceptsClient: true
