---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-workload-availability
policyDefaults:
  namespace: policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - workload-availability-operator

  categories:
    - "CM Configuration Management"
  controls:
    - "CM-2 Baseline Configuration"
  standards:
    - "NIST SP 800-53"

  policyLabels:
    policy_gen.name: workload-availability-operator

  severity: medium

placementBindingDefaults:
  name: "workload-availability-binding"

policies:
  - name: workload-availability-operator
    description: "Installs Fence Agent, Self Node Remediation, Node Healthcheck, and Machine Deletion Operators"
    manifests:
      - path: namespace.yaml
      - path: fence-agent-operatorpolicy.yaml
      - path: self-node-operatorpolicy.yaml
      - path: node-healthcheck-operatorpolicy.yaml
      - path: node-remediation-console.yaml
        name: node-remediation-console
        extraDependencies:
          - apiVersion: policy.open-cluster-management.io/v1beta1
            kind: OperatorPolicy
            name: node-healthcheck-operator-install
            compliance: "Compliant"
      - path: machine-deletion-operatorpolicy.yaml

  - name: workload-availability-remediation
    description: "Configures example node remediation using Self Node Remediation or Fence Agent Operator"
    dependencies:
      - name: workload-availability-operator
        compliance: "Compliant"
    manifests:
      ## Uncomment this block to use far, and comment the snr block below
      # - path: far-nhc-remediation/nodehealthcheck.yaml
      #   name: far-nodehealhcheck
      # - path: far-nhc-remediation/far-template.yaml
      #   name: far-outofservicetaint-remediation
      # - path: far-nhc-remediation/mdr-template.yaml
      #   name: mdr-remediation

      - path: snr-nhc-remediation/nodehealthcheck.yaml
        name: snr-nodehealhcheck
      - path: snr-nhc-remediation/snr-outofservicetaint-template.yaml
        name: snr-outofservicetaint-remediation
      - path: snr-nhc-remediation/mdr-template.yaml
        name: mdr-remediation

policySets:
  - name: workload-availability-operator
    placement:
      placementName: "ft-workload-availability--enabled"
