---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gen-policy-opentelemetry
policyDefaults:
  namespace: policies
  remediationAction: enforce
  consolidateManifests: false
  policySets:
    - opentelemetry-operator

  categories:
    - "CM Configuration Management"
  controls:
    - "CM-2 Baseline Configuration"
  standards:
    - "NIST SP 800-53"

  policyLabels:
    policy_gen.name: opentelemetry-operator

  severity: medium

placementBindingDefaults:
  name: "opentelemetry-binding"

policies:
  - name: opentelemetry-operator
    description: "Install OpenTelemetry Operator"
    remediationAction: enforce
    manifests:
      - path: namespace.yaml
        name: otel-namespace

      - path: operatorpolicy.yaml

      - path: clusterrole.yaml
        name: otel-clusterrole

      - path: clusterrolebinding.yaml
        name: otel-clusterrolebinding

policySets:
  - name: opentelemetry-operator
    placement:
      placementName: "ft-opentelemetry--enabled"
